spring:
  application:
    name: ejercicio7_servidor_gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: servCursos
          uri: lb://05-servicio-cursos
          predicates:
            - Path=/scursos/**
          filters:
            - RewritePath=/scursos/*, / # sustituye '/scursos/' por /

        - id: servFormacion
          uri: lb://05-servicio-formacion
          predicates:
            - Path=/sformacion/**
          filters:
            - RewritePath=/sformacion/*, / # sustituye '/sformacion/' por /

server:
  port: 9000

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka

#aqui
logging:
  level:
    root: INFO
    #'[org.springframework.cloud.gateway]': TRACE
    #'[org.springframework.cloud.gateway.filter.LoadBalancerClientFilter]': TRACE
    #'[org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator]': INFO
    #'[org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping]': DEBUG
    #'[org.springframework.cloud.gateway.filter.GlobalFilter]': TRACE
    #'[com.netflix.discovery]': DEBUG
    #'[com.netflix.eureka]': DEBUG
    #'[org.springframework.cloud.gateway.filter.NettyRoutingFilter]': TRACE
    #'[org.springframework.web.cors]': TRACE
    #'[org.springframework.http.server.reactive]': TRACE
    #'[org.springframework.web.reactive]': TRACE
    #'[reactor.netty]': DEBUG
    #'[redisratelimiter]': DEBUG
    #'[org.springframework.web]': TRACE
    #'[org.springframework.http]': TRACE


  #pattern:
    #console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

