spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/hotel_db?serverTimezone=UTC
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
      naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  devtools:
    restart:
      enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    # mejoras adicionales
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5 # determina con qué frecuencia el cliente obtiene el registro actualizado de Eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # determina con qué frecuencia el cliente envía latidos a Eureka
    lease-expiration-duration-in-seconds: 20 # determina cuánto tiempo debe pasar sin recibir un latido para que Eureka considere que la instancia ha expirado

# Asiganmos un puerto de forma aleatoria
server:
  port: 0

# Configuración Spring Doc
springdoc:
  packages-to-scan: com.hotel.controller
  paths-to-match: /**
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-operation-id: true
